name: Tests

on: ["push", "pull_request"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov=bimmer_connected --timeout=10 test
      - name: Upload coverage data to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: "pytest-${{ matrix.test-name }}"
          COVERALLS_PARALLEL: true
        run: |
          coveralls -v --service=github

  coveralls:
    name: Indicate completion to coveralls.io
    needs: pytest
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_PARALLEL: true
      run: |
        pip install --upgrade coveralls
        coveralls -v --service=github --finish

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt
      - name: Test with flake8
        run: |
          flake8 bimmer_connected test
        # continue-on-error: true
  
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt
      - name: Test with pylint
        run: |
          pylint -j4 bimmer_connected test
        # continue-on-error: true
# -r requirements-docs.txt